package van.pojo;

import java.util.Date;

public class Construction {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction.design_id
     *
     * @mbg.generated
     */
    private Integer designId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction.charge_user_id
     *
     * @mbg.generated
     */
    private Integer chargeUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction.worker_id
     *
     * @mbg.generated
     */
    private Integer workerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction.start_time
     *
     * @mbg.generated
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction.end_time
     *
     * @mbg.generated
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction.note_taker
     *
     * @mbg.generated
     */
    private String noteTaker;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction.record_time
     *
     * @mbg.generated
     */
    private Date recordTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction.id
     *
     * @return the value of construction.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction.id
     *
     * @param id the value for construction.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction.design_id
     *
     * @return the value of construction.design_id
     *
     * @mbg.generated
     */
    public Integer getDesignId() {
        return designId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction.design_id
     *
     * @param designId the value for construction.design_id
     *
     * @mbg.generated
     */
    public void setDesignId(Integer designId) {
        this.designId = designId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction.charge_user_id
     *
     * @return the value of construction.charge_user_id
     *
     * @mbg.generated
     */
    public Integer getChargeUserId() {
        return chargeUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction.charge_user_id
     *
     * @param chargeUserId the value for construction.charge_user_id
     *
     * @mbg.generated
     */
    public void setChargeUserId(Integer chargeUserId) {
        this.chargeUserId = chargeUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction.worker_id
     *
     * @return the value of construction.worker_id
     *
     * @mbg.generated
     */
    public Integer getWorkerId() {
        return workerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction.worker_id
     *
     * @param workerId the value for construction.worker_id
     *
     * @mbg.generated
     */
    public void setWorkerId(Integer workerId) {
        this.workerId = workerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction.start_time
     *
     * @return the value of construction.start_time
     *
     * @mbg.generated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction.start_time
     *
     * @param startTime the value for construction.start_time
     *
     * @mbg.generated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction.end_time
     *
     * @return the value of construction.end_time
     *
     * @mbg.generated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction.end_time
     *
     * @param endTime the value for construction.end_time
     *
     * @mbg.generated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction.note_taker
     *
     * @return the value of construction.note_taker
     *
     * @mbg.generated
     */
    public String getNoteTaker() {
        return noteTaker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction.note_taker
     *
     * @param noteTaker the value for construction.note_taker
     *
     * @mbg.generated
     */
    public void setNoteTaker(String noteTaker) {
        this.noteTaker = noteTaker == null ? null : noteTaker.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction.record_time
     *
     * @return the value of construction.record_time
     *
     * @mbg.generated
     */
    public Date getRecordTime() {
        return recordTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction.record_time
     *
     * @param recordTime the value for construction.record_time
     *
     * @mbg.generated
     */
    public void setRecordTime(Date recordTime) {
        this.recordTime = recordTime;
    }
}