package van.pojo;

public class ConstructionPersonList {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction_person_list.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction_person_list.construction_id
     *
     * @mbg.generated
     */
    private Integer constructionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column construction_person_list.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction_person_list.id
     *
     * @return the value of construction_person_list.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction_person_list.id
     *
     * @param id the value for construction_person_list.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction_person_list.construction_id
     *
     * @return the value of construction_person_list.construction_id
     *
     * @mbg.generated
     */
    public Integer getConstructionId() {
        return constructionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction_person_list.construction_id
     *
     * @param constructionId the value for construction_person_list.construction_id
     *
     * @mbg.generated
     */
    public void setConstructionId(Integer constructionId) {
        this.constructionId = constructionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column construction_person_list.user_id
     *
     * @return the value of construction_person_list.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column construction_person_list.user_id
     *
     * @param userId the value for construction_person_list.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}