package van.pojo;

import java.util.Date;

public class DetailToolsOutIn {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detail_tools_out_in.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detail_tools_out_in.number
     *
     * @mbg.generated
     */
    private Integer number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detail_tools_out_in.tools_out_in_id
     *
     * @mbg.generated
     */
    private Integer toolsOutInId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detail_tools_out_in.warehousing_id
     *
     * @mbg.generated
     */
    private Integer warehousingId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detail_tools_out_in.tools_id
     *
     * @mbg.generated
     */
    private Integer toolsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detail_tools_out_in.state
     *
     * @mbg.generated
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detail_tools_out_in.note_taker
     *
     * @mbg.generated
     */
    private String noteTaker;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detail_tools_out_in.record_time
     *
     * @mbg.generated
     */
    private Date recordTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detail_tools_out_in.id
     *
     * @return the value of detail_tools_out_in.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detail_tools_out_in.id
     *
     * @param id the value for detail_tools_out_in.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detail_tools_out_in.number
     *
     * @return the value of detail_tools_out_in.number
     *
     * @mbg.generated
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detail_tools_out_in.number
     *
     * @param number the value for detail_tools_out_in.number
     *
     * @mbg.generated
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detail_tools_out_in.tools_out_in_id
     *
     * @return the value of detail_tools_out_in.tools_out_in_id
     *
     * @mbg.generated
     */
    public Integer getToolsOutInId() {
        return toolsOutInId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detail_tools_out_in.tools_out_in_id
     *
     * @param toolsOutInId the value for detail_tools_out_in.tools_out_in_id
     *
     * @mbg.generated
     */
    public void setToolsOutInId(Integer toolsOutInId) {
        this.toolsOutInId = toolsOutInId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detail_tools_out_in.warehousing_id
     *
     * @return the value of detail_tools_out_in.warehousing_id
     *
     * @mbg.generated
     */
    public Integer getWarehousingId() {
        return warehousingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detail_tools_out_in.warehousing_id
     *
     * @param warehousingId the value for detail_tools_out_in.warehousing_id
     *
     * @mbg.generated
     */
    public void setWarehousingId(Integer warehousingId) {
        this.warehousingId = warehousingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detail_tools_out_in.tools_id
     *
     * @return the value of detail_tools_out_in.tools_id
     *
     * @mbg.generated
     */
    public Integer getToolsId() {
        return toolsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detail_tools_out_in.tools_id
     *
     * @param toolsId the value for detail_tools_out_in.tools_id
     *
     * @mbg.generated
     */
    public void setToolsId(Integer toolsId) {
        this.toolsId = toolsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detail_tools_out_in.state
     *
     * @return the value of detail_tools_out_in.state
     *
     * @mbg.generated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detail_tools_out_in.state
     *
     * @param state the value for detail_tools_out_in.state
     *
     * @mbg.generated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detail_tools_out_in.note_taker
     *
     * @return the value of detail_tools_out_in.note_taker
     *
     * @mbg.generated
     */
    public String getNoteTaker() {
        return noteTaker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detail_tools_out_in.note_taker
     *
     * @param noteTaker the value for detail_tools_out_in.note_taker
     *
     * @mbg.generated
     */
    public void setNoteTaker(String noteTaker) {
        this.noteTaker = noteTaker == null ? null : noteTaker.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detail_tools_out_in.record_time
     *
     * @return the value of detail_tools_out_in.record_time
     *
     * @mbg.generated
     */
    public Date getRecordTime() {
        return recordTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detail_tools_out_in.record_time
     *
     * @param recordTime the value for detail_tools_out_in.record_time
     *
     * @mbg.generated
     */
    public void setRecordTime(Date recordTime) {
        this.recordTime = recordTime;
    }
}