package van.pojo;

import java.util.Date;

public class DetailOutInWarehousing {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detail_out_in_warehousing.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detail_out_in_warehousing.materiel_id
     *
     * @mbg.generated
     */
    private Integer materielId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detail_out_in_warehousing.out_in_warehousing_id
     *
     * @mbg.generated
     */
    private Integer outInWarehousingId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detail_out_in_warehousing.warehousing_id
     *
     * @mbg.generated
     */
    private Integer warehousingId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detail_out_in_warehousing.number
     *
     * @mbg.generated
     */
    private String number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detail_out_in_warehousing.state
     *
     * @mbg.generated
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detail_out_in_warehousing.note_taker
     *
     * @mbg.generated
     */
    private String noteTaker;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detail_out_in_warehousing.record_time
     *
     * @mbg.generated
     */
    private Date recordTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detail_out_in_warehousing.id
     *
     * @return the value of detail_out_in_warehousing.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detail_out_in_warehousing.id
     *
     * @param id the value for detail_out_in_warehousing.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detail_out_in_warehousing.materiel_id
     *
     * @return the value of detail_out_in_warehousing.materiel_id
     *
     * @mbg.generated
     */
    public Integer getMaterielId() {
        return materielId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detail_out_in_warehousing.materiel_id
     *
     * @param materielId the value for detail_out_in_warehousing.materiel_id
     *
     * @mbg.generated
     */
    public void setMaterielId(Integer materielId) {
        this.materielId = materielId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detail_out_in_warehousing.out_in_warehousing_id
     *
     * @return the value of detail_out_in_warehousing.out_in_warehousing_id
     *
     * @mbg.generated
     */
    public Integer getOutInWarehousingId() {
        return outInWarehousingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detail_out_in_warehousing.out_in_warehousing_id
     *
     * @param outInWarehousingId the value for detail_out_in_warehousing.out_in_warehousing_id
     *
     * @mbg.generated
     */
    public void setOutInWarehousingId(Integer outInWarehousingId) {
        this.outInWarehousingId = outInWarehousingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detail_out_in_warehousing.warehousing_id
     *
     * @return the value of detail_out_in_warehousing.warehousing_id
     *
     * @mbg.generated
     */
    public Integer getWarehousingId() {
        return warehousingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detail_out_in_warehousing.warehousing_id
     *
     * @param warehousingId the value for detail_out_in_warehousing.warehousing_id
     *
     * @mbg.generated
     */
    public void setWarehousingId(Integer warehousingId) {
        this.warehousingId = warehousingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detail_out_in_warehousing.number
     *
     * @return the value of detail_out_in_warehousing.number
     *
     * @mbg.generated
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detail_out_in_warehousing.number
     *
     * @param number the value for detail_out_in_warehousing.number
     *
     * @mbg.generated
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detail_out_in_warehousing.state
     *
     * @return the value of detail_out_in_warehousing.state
     *
     * @mbg.generated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detail_out_in_warehousing.state
     *
     * @param state the value for detail_out_in_warehousing.state
     *
     * @mbg.generated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detail_out_in_warehousing.note_taker
     *
     * @return the value of detail_out_in_warehousing.note_taker
     *
     * @mbg.generated
     */
    public String getNoteTaker() {
        return noteTaker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detail_out_in_warehousing.note_taker
     *
     * @param noteTaker the value for detail_out_in_warehousing.note_taker
     *
     * @mbg.generated
     */
    public void setNoteTaker(String noteTaker) {
        this.noteTaker = noteTaker == null ? null : noteTaker.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detail_out_in_warehousing.record_time
     *
     * @return the value of detail_out_in_warehousing.record_time
     *
     * @mbg.generated
     */
    public Date getRecordTime() {
        return recordTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detail_out_in_warehousing.record_time
     *
     * @param recordTime the value for detail_out_in_warehousing.record_time
     *
     * @mbg.generated
     */
    public void setRecordTime(Date recordTime) {
        this.recordTime = recordTime;
    }
}