package van.pojo;

import java.util.Date;

public class MaterielActual {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column materiel_actual.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column materiel_actual.materiel_plan_id
     *
     * @mbg.generated
     */
    private Integer materielPlanId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column materiel_actual.actual_num
     *
     * @mbg.generated
     */
    private Integer actualNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column materiel_actual.actual_time
     *
     * @mbg.generated
     */
    private Date actualTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column materiel_actual.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column materiel_actual.note_taker
     *
     * @mbg.generated
     */
    private String noteTaker;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column materiel_actual.record_time
     *
     * @mbg.generated
     */
    private Date recordTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column materiel_actual.id
     *
     * @return the value of materiel_actual.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column materiel_actual.id
     *
     * @param id the value for materiel_actual.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column materiel_actual.materiel_plan_id
     *
     * @return the value of materiel_actual.materiel_plan_id
     *
     * @mbg.generated
     */
    public Integer getMaterielPlanId() {
        return materielPlanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column materiel_actual.materiel_plan_id
     *
     * @param materielPlanId the value for materiel_actual.materiel_plan_id
     *
     * @mbg.generated
     */
    public void setMaterielPlanId(Integer materielPlanId) {
        this.materielPlanId = materielPlanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column materiel_actual.actual_num
     *
     * @return the value of materiel_actual.actual_num
     *
     * @mbg.generated
     */
    public Integer getActualNum() {
        return actualNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column materiel_actual.actual_num
     *
     * @param actualNum the value for materiel_actual.actual_num
     *
     * @mbg.generated
     */
    public void setActualNum(Integer actualNum) {
        this.actualNum = actualNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column materiel_actual.actual_time
     *
     * @return the value of materiel_actual.actual_time
     *
     * @mbg.generated
     */
    public Date getActualTime() {
        return actualTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column materiel_actual.actual_time
     *
     * @param actualTime the value for materiel_actual.actual_time
     *
     * @mbg.generated
     */
    public void setActualTime(Date actualTime) {
        this.actualTime = actualTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column materiel_actual.user_id
     *
     * @return the value of materiel_actual.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column materiel_actual.user_id
     *
     * @param userId the value for materiel_actual.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column materiel_actual.note_taker
     *
     * @return the value of materiel_actual.note_taker
     *
     * @mbg.generated
     */
    public String getNoteTaker() {
        return noteTaker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column materiel_actual.note_taker
     *
     * @param noteTaker the value for materiel_actual.note_taker
     *
     * @mbg.generated
     */
    public void setNoteTaker(String noteTaker) {
        this.noteTaker = noteTaker == null ? null : noteTaker.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column materiel_actual.record_time
     *
     * @return the value of materiel_actual.record_time
     *
     * @mbg.generated
     */
    public Date getRecordTime() {
        return recordTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column materiel_actual.record_time
     *
     * @param recordTime the value for materiel_actual.record_time
     *
     * @mbg.generated
     */
    public void setRecordTime(Date recordTime) {
        this.recordTime = recordTime;
    }
}