package van.pojo;

import java.util.Date;

public class OutInWarehousing {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_in_warehousing.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_in_warehousing.category
     *
     * @mbg.generated
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_in_warehousing.states
     *
     * @mbg.generated
     */
    private String states;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_in_warehousing.exe_user_id
     *
     * @mbg.generated
     */
    private Integer exeUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_in_warehousing.approver_user_id
     *
     * @mbg.generated
     */
    private Integer approverUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_in_warehousing.application_time
     *
     * @mbg.generated
     */
    private Date applicationTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_in_warehousing.execution_time
     *
     * @mbg.generated
     */
    private Date executionTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_in_warehousing.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_in_warehousing.note_taker
     *
     * @mbg.generated
     */
    private String noteTaker;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_in_warehousing.record_time
     *
     * @mbg.generated
     */
    private Date recordTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_in_warehousing.id
     *
     * @return the value of out_in_warehousing.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_in_warehousing.id
     *
     * @param id the value for out_in_warehousing.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_in_warehousing.category
     *
     * @return the value of out_in_warehousing.category
     *
     * @mbg.generated
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_in_warehousing.category
     *
     * @param category the value for out_in_warehousing.category
     *
     * @mbg.generated
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_in_warehousing.states
     *
     * @return the value of out_in_warehousing.states
     *
     * @mbg.generated
     */
    public String getStates() {
        return states;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_in_warehousing.states
     *
     * @param states the value for out_in_warehousing.states
     *
     * @mbg.generated
     */
    public void setStates(String states) {
        this.states = states == null ? null : states.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_in_warehousing.exe_user_id
     *
     * @return the value of out_in_warehousing.exe_user_id
     *
     * @mbg.generated
     */
    public Integer getExeUserId() {
        return exeUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_in_warehousing.exe_user_id
     *
     * @param exeUserId the value for out_in_warehousing.exe_user_id
     *
     * @mbg.generated
     */
    public void setExeUserId(Integer exeUserId) {
        this.exeUserId = exeUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_in_warehousing.approver_user_id
     *
     * @return the value of out_in_warehousing.approver_user_id
     *
     * @mbg.generated
     */
    public Integer getApproverUserId() {
        return approverUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_in_warehousing.approver_user_id
     *
     * @param approverUserId the value for out_in_warehousing.approver_user_id
     *
     * @mbg.generated
     */
    public void setApproverUserId(Integer approverUserId) {
        this.approverUserId = approverUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_in_warehousing.application_time
     *
     * @return the value of out_in_warehousing.application_time
     *
     * @mbg.generated
     */
    public Date getApplicationTime() {
        return applicationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_in_warehousing.application_time
     *
     * @param applicationTime the value for out_in_warehousing.application_time
     *
     * @mbg.generated
     */
    public void setApplicationTime(Date applicationTime) {
        this.applicationTime = applicationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_in_warehousing.execution_time
     *
     * @return the value of out_in_warehousing.execution_time
     *
     * @mbg.generated
     */
    public Date getExecutionTime() {
        return executionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_in_warehousing.execution_time
     *
     * @param executionTime the value for out_in_warehousing.execution_time
     *
     * @mbg.generated
     */
    public void setExecutionTime(Date executionTime) {
        this.executionTime = executionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_in_warehousing.remarks
     *
     * @return the value of out_in_warehousing.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_in_warehousing.remarks
     *
     * @param remarks the value for out_in_warehousing.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_in_warehousing.note_taker
     *
     * @return the value of out_in_warehousing.note_taker
     *
     * @mbg.generated
     */
    public String getNoteTaker() {
        return noteTaker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_in_warehousing.note_taker
     *
     * @param noteTaker the value for out_in_warehousing.note_taker
     *
     * @mbg.generated
     */
    public void setNoteTaker(String noteTaker) {
        this.noteTaker = noteTaker == null ? null : noteTaker.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_in_warehousing.record_time
     *
     * @return the value of out_in_warehousing.record_time
     *
     * @mbg.generated
     */
    public Date getRecordTime() {
        return recordTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_in_warehousing.record_time
     *
     * @param recordTime the value for out_in_warehousing.record_time
     *
     * @mbg.generated
     */
    public void setRecordTime(Date recordTime) {
        this.recordTime = recordTime;
    }
}