package van.pojo;

import java.util.Date;

public class SupplierMateriel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_materiel.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_materiel.supplier_id
     *
     * @mbg.generated
     */
    private Integer supplierId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_materiel.materiel_id
     *
     * @mbg.generated
     */
    private Integer materielId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_materiel.price
     *
     * @mbg.generated
     */
    private Long price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_materiel.number
     *
     * @mbg.generated
     */
    private Integer number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_materiel.time
     *
     * @mbg.generated
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_materiel.note_taker
     *
     * @mbg.generated
     */
    private String noteTaker;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier_materiel.record_time
     *
     * @mbg.generated
     */
    private Date recordTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_materiel.id
     *
     * @return the value of supplier_materiel.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_materiel.id
     *
     * @param id the value for supplier_materiel.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_materiel.supplier_id
     *
     * @return the value of supplier_materiel.supplier_id
     *
     * @mbg.generated
     */
    public Integer getSupplierId() {
        return supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_materiel.supplier_id
     *
     * @param supplierId the value for supplier_materiel.supplier_id
     *
     * @mbg.generated
     */
    public void setSupplierId(Integer supplierId) {
        this.supplierId = supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_materiel.materiel_id
     *
     * @return the value of supplier_materiel.materiel_id
     *
     * @mbg.generated
     */
    public Integer getMaterielId() {
        return materielId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_materiel.materiel_id
     *
     * @param materielId the value for supplier_materiel.materiel_id
     *
     * @mbg.generated
     */
    public void setMaterielId(Integer materielId) {
        this.materielId = materielId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_materiel.price
     *
     * @return the value of supplier_materiel.price
     *
     * @mbg.generated
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_materiel.price
     *
     * @param price the value for supplier_materiel.price
     *
     * @mbg.generated
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_materiel.number
     *
     * @return the value of supplier_materiel.number
     *
     * @mbg.generated
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_materiel.number
     *
     * @param number the value for supplier_materiel.number
     *
     * @mbg.generated
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_materiel.time
     *
     * @return the value of supplier_materiel.time
     *
     * @mbg.generated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_materiel.time
     *
     * @param time the value for supplier_materiel.time
     *
     * @mbg.generated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_materiel.note_taker
     *
     * @return the value of supplier_materiel.note_taker
     *
     * @mbg.generated
     */
    public String getNoteTaker() {
        return noteTaker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_materiel.note_taker
     *
     * @param noteTaker the value for supplier_materiel.note_taker
     *
     * @mbg.generated
     */
    public void setNoteTaker(String noteTaker) {
        this.noteTaker = noteTaker == null ? null : noteTaker.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier_materiel.record_time
     *
     * @return the value of supplier_materiel.record_time
     *
     * @mbg.generated
     */
    public Date getRecordTime() {
        return recordTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier_materiel.record_time
     *
     * @param recordTime the value for supplier_materiel.record_time
     *
     * @mbg.generated
     */
    public void setRecordTime(Date recordTime) {
        this.recordTime = recordTime;
    }
}