package van.pojo;

import java.util.Date;

public class Worker {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker.identification
     *
     * @mbg.generated
     */
    private String identification;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker.note_taker
     *
     * @mbg.generated
     */
    private String noteTaker;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker.record_time
     *
     * @mbg.generated
     */
    private Date recordTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker.id
     *
     * @return the value of worker.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker.id
     *
     * @param id the value for worker.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker.name
     *
     * @return the value of worker.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker.name
     *
     * @param name the value for worker.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker.identification
     *
     * @return the value of worker.identification
     *
     * @mbg.generated
     */
    public String getIdentification() {
        return identification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker.identification
     *
     * @param identification the value for worker.identification
     *
     * @mbg.generated
     */
    public void setIdentification(String identification) {
        this.identification = identification == null ? null : identification.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker.note_taker
     *
     * @return the value of worker.note_taker
     *
     * @mbg.generated
     */
    public String getNoteTaker() {
        return noteTaker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker.note_taker
     *
     * @param noteTaker the value for worker.note_taker
     *
     * @mbg.generated
     */
    public void setNoteTaker(String noteTaker) {
        this.noteTaker = noteTaker == null ? null : noteTaker.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker.record_time
     *
     * @return the value of worker.record_time
     *
     * @mbg.generated
     */
    public Date getRecordTime() {
        return recordTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker.record_time
     *
     * @param recordTime the value for worker.record_time
     *
     * @mbg.generated
     */
    public void setRecordTime(Date recordTime) {
        this.recordTime = recordTime;
    }
}