package van.dao;

import java.util.List;
import van.pojo.Construction;

public interface ConstructionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction
     *
     * @mbg.generated
     */
    int insert(Construction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction
     *
     * @mbg.generated
     */
    Construction selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction
     *
     * @mbg.generated
     */
    List<Construction> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Construction record);
}