package van.dao;

import java.util.List;
import van.pojo.ConstructionPersonList;

public interface ConstructionPersonListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_person_list
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_person_list
     *
     * @mbg.generated
     */
    int insert(ConstructionPersonList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_person_list
     *
     * @mbg.generated
     */
    ConstructionPersonList selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_person_list
     *
     * @mbg.generated
     */
    List<ConstructionPersonList> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_person_list
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ConstructionPersonList record);
}