package van.dao;

import java.util.List;
import van.pojo.DetailOutInWarehousing;

public interface DetailOutInWarehousingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail_out_in_warehousing
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail_out_in_warehousing
     *
     * @mbg.generated
     */
    int insert(DetailOutInWarehousing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail_out_in_warehousing
     *
     * @mbg.generated
     */
    DetailOutInWarehousing selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail_out_in_warehousing
     *
     * @mbg.generated
     */
    List<DetailOutInWarehousing> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detail_out_in_warehousing
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DetailOutInWarehousing record);
}