package van.dao;

import java.util.List;
import van.pojo.MaterielStock;

public interface MaterielStockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table materiel_stock
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table materiel_stock
     *
     * @mbg.generated
     */
    int insert(MaterielStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table materiel_stock
     *
     * @mbg.generated
     */
    MaterielStock selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table materiel_stock
     *
     * @mbg.generated
     */
    List<MaterielStock> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table materiel_stock
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MaterielStock record);
}