package van.dao;

import java.util.List;
import van.pojo.MaterielActual;

public interface MaterielActualMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table materiel_actual
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table materiel_actual
     *
     * @mbg.generated
     */
    int insert(MaterielActual record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table materiel_actual
     *
     * @mbg.generated
     */
    MaterielActual selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table materiel_actual
     *
     * @mbg.generated
     */
    List<MaterielActual> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table materiel_actual
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MaterielActual record);
}