package van.dao;

import java.util.List;
import van.pojo.MaterielPlan;

public interface MaterielPlanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table materiel_plan
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table materiel_plan
     *
     * @mbg.generated
     */
    int insert(MaterielPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table materiel_plan
     *
     * @mbg.generated
     */
    MaterielPlan selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table materiel_plan
     *
     * @mbg.generated
     */
    List<MaterielPlan> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table materiel_plan
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MaterielPlan record);
}