package van.dao;

import java.util.List;
import van.pojo.ModuleAuth;

public interface ModuleAuthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_auth
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_auth
     *
     * @mbg.generated
     */
    int insert(ModuleAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_auth
     *
     * @mbg.generated
     */
    ModuleAuth selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_auth
     *
     * @mbg.generated
     */
    List<ModuleAuth> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_auth
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ModuleAuth record);
}