package van.dao;

import java.util.List;
import van.pojo.PostAuth;

public interface PostAuthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_auth
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_auth
     *
     * @mbg.generated
     */
    int insert(PostAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_auth
     *
     * @mbg.generated
     */
    PostAuth selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_auth
     *
     * @mbg.generated
     */
    List<PostAuth> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_auth
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PostAuth record);
}