package van.dao;

import java.util.List;
import van.pojo.Projects;

public interface ProjectsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projects
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projects
     *
     * @mbg.generated
     */
    int insert(Projects record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projects
     *
     * @mbg.generated
     */
    Projects selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projects
     *
     * @mbg.generated
     */
    List<Projects> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projects
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Projects record);
}