package van.dao;

import java.util.List;
import van.pojo.SupplierMateriel;

public interface SupplierMaterielMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_materiel
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_materiel
     *
     * @mbg.generated
     */
    int insert(SupplierMateriel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_materiel
     *
     * @mbg.generated
     */
    SupplierMateriel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_materiel
     *
     * @mbg.generated
     */
    List<SupplierMateriel> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier_materiel
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SupplierMateriel record);
}