package van.dao;

import java.util.List;
import van.pojo.Tools;

public interface ToolsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tools
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tools
     *
     * @mbg.generated
     */
    int insert(Tools record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tools
     *
     * @mbg.generated
     */
    Tools selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tools
     *
     * @mbg.generated
     */
    List<Tools> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tools
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Tools record);
}