package van.dao;

import java.util.List;
import van.pojo.ToolsStock;

public interface ToolsStockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tools_stock
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tools_stock
     *
     * @mbg.generated
     */
    int insert(ToolsStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tools_stock
     *
     * @mbg.generated
     */
    ToolsStock selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tools_stock
     *
     * @mbg.generated
     */
    List<ToolsStock> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tools_stock
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ToolsStock record);
}