package van.dao;

import java.util.List;
import van.pojo.UserDepartmentPost;

public interface UserDepartmentPostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_department_post
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer categoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_department_post
     *
     * @mbg.generated
     */
    int insert(UserDepartmentPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_department_post
     *
     * @mbg.generated
     */
    UserDepartmentPost selectByPrimaryKey(Integer categoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_department_post
     *
     * @mbg.generated
     */
    List<UserDepartmentPost> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_department_post
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserDepartmentPost record);
}