package van.dao;

import java.util.List;
import van.pojo.Warehousing;

public interface WarehousingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehousing
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehousing
     *
     * @mbg.generated
     */
    int insert(Warehousing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehousing
     *
     * @mbg.generated
     */
    Warehousing selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehousing
     *
     * @mbg.generated
     */
    List<Warehousing> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehousing
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Warehousing record);
}